---
title: "Look at random forest"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown


```{r load_rf}
library(tidyverse)
library(ranger)
library(pdp)
load("data/ES-RF.RDA")


wfs <- readRDS("data/allresults_20250308.rds")
      
dat.predictors <-  wfs[, c(81:107,120:123)]

# drop log-transform
dat.predictors <- dat.predictors[, !grepl("log", colnames(dat.predictors))]

```


```{r pca}
library(ggbiplot)
pca.predictors <- prcomp(dat.predictors,
                         scale. = TRUE, center = TRUE)

ggbiplot(pca.predictors, c(2,3))
```

## Including Plots

You can also embed plots, for example:

```{r }


    if(!exists("pollinators_base.ann_agr_pland.pdp2")) {
        dat <- data.frame(y = wfs$delta_pollinators_max.margin, orig = wfs$pollinators_base, dat.predictors)
        pollinators_base.ann_agr_pland.pdp2 <- pdp::partial(pollinators_base.rf, train = dat, pred.var = "ann_agr_pland", ice = TRUE, rug = TRUE)
        pollinators_margin.ann_agr_pland.pdp2 <- pdp::partial(pollinators_margin.rf, train = dat, pred.var = "ann_agr_pland", ice = TRUE, rug = TRUE)
        pollinators_base.ntr_pland.pdp2 <- pdp::partial(pollinators_base.rf, train = dat, pred.var = "ntr_pland", ice = TRUE, rug = TRUE)
        pollinators_margin.ntr_pland.pdp2 <- pdp::partial(pollinators_margin.rf, train = dat, pred.var = "ntr_pland", ice = TRUE, rug = TRUE)
        rm(dat)
    }

    if(!exists("n_export_base.ann_agr_pland.pdp2")) {
        dat <- data.frame(y = wfs$delta_n_export_max.margin, orig = wfs$n_export_base, dat.predictors)
        n_export_base.ann_agr_pland.pdp <- partial(n_export_base.rf, train = dat, pred.var = "ann_agr_pland")
        n_export_margin.ann_agr_pland.pdp <- partial(n_export_margin.rf, train = dat, pred.var = "ann_agr_pland")
        n_export_base.ntr_pland.pdp <- partial(n_export_base.rf, train = dat, pred.var = "ntr_pland")
        n_export_margin.ntr_pland.pdp <- partial(n_export_margin.rf, train = dat, pred.var = "ntr_pland")
        rm(dat)
    }

    if(!exists("sed_export_base.ann_agr_pland.pdp2")) {
        dat <- data.frame(y = wfs$delta_sed_max.margin, orig = wfs$sed_export_base, dat.predictors)
        sed_export_base.ann_agr_pland.pdp <- partial(sed_export_base.rf, train = dat, pred.var = "ann_agr_pland")
        sed_export_margin.ann_agr_pland.pdp <- partial(sed_export_margin.rf, train = dat, pred.var = "ann_agr_pland")
        sed_export_base.ntr_pland.pdp <- partial(sed_export_base.rf, train = dat, pred.var = "ntr_pland")
        sed_export_margin.ntr_pland.pdp <- partial(sed_export_margin.rf, train = dat, pred.var = "ntr_pland")
        rm(dat)
    }

    if(!exists("qb_base.ann_agr_pland.pdp2")) {
        dat <- data.frame(y = wfs$delta_qb_max.margin, orig = wfs$qb_base, dat.predictors)
        qb_base.ann_agr_pland.pdp <- partial(qb_base.rf, train = dat, pred.var = "ann_agr_pland")
        qb_margin.ann_agr_pland.pdp <- partial(qb_margin.rf, train = dat, pred.var = "ann_agr_pland")
        qb_base.ntr_pland.pdp <- partial(qb_base.rf, train = dat, pred.var = "ntr_pland")
        qb_margin.ntr_pland.pdp <- partial(qb_margin.rf, train = dat, pred.var = "ntr_pland")
        rm(dat)
    }

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
