---
title: "Landscape models using log transform"
---

```{r setup, echo = FALSE}
library(tidyverse)
library(performance)
library(psych)
library(mgcv)
library(ggeffects)
library(piecewiseSEM)
source("R/utils-plot.r")

wfs <- readRDS("data/maxwfsresults_20241217_fix.rds")
lsm <- read.csv("data/lsm_reduced.csv") %>% 
  mutate(hu = gsub("hu", "", hu))

wfs_lsm <- wfs %>% left_join(lsm, by = "hu") %>%
  select(c(hu, huc2, name, margin.ha, lu_ta,
           pollinators_base:sed_export_base, 
           pollinators_max:sed_export_max, 
           delta_pollinators:delta_sed, 
           fields_max, field.ha, margin.ha, 
           lu_shdi:ntr_frac_mn)) %>%
  mutate(prn_ann_ratio = log(prn_agr_pland/ann_agr_pland),
         prn_pagr = 100*(prn_agr_pland/(ann_agr_pland+prn_agr_pland)),
         field_pland = field.ha/lu_ta,
         margin_dens = margin.ha/lu_ta,
         log.delta_pollinators = log(delta_pollinators),
         log.delta_qb = log(ifelse(delta_qb>0,delta_qb,0.0001)))

```

## Pollinator models

### Pollinator delta

```{r pollinator_delta}

pol.lm0 <- gam(log.delta_pollinators ~ margin_dens, data = wfs_lsm)
pol.gam0 <- gam(log.delta_pollinators ~ s(margin_dens), data = wfs_lsm)

anova(pol.lm0, pol.gam0)

pol.gam1 <- gam(log.delta_pollinators ~ s(ann_agr_pland) + s(aglu_iji) + s(prn_agr_pland) + s(aglu_frac_mn) + s(margin_dens) + s(lu_shdi), 
                data = wfs_lsm)

performance::compare_performance(pol.lm0, pol.gam0, pol.gam1)

summary(pol.gam1)

concurvity(pol.gam1)

```

```{r plot_pol}

polplot.df <- plot_fun(pol.gam1, 
                       c("ann_agr_pland", "aglu_iji", "prn_agr_pland", "aglu_frac_mn", "margin_dens"),
                       wfs_lsm)

ggplot(polplot.df[[1]], aes(x, log.delta_pollinators)) +  
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.2) + geom_line() +
  geom_point(data = polplot.df[[2]], 
             mapping = aes(color = margin_dens), 
             size = 0.6) + scale_color_continuous(type = "viridis") +
  facet_wrap(~pred.var, scales = "free_x") +
  egg::theme_article()

```


```{r plot_pol0}

polplot0.df <- plot_fun(pol.gam0, 
                       "margin_dens",
                       wfs_lsm)

ggplot(polplot0.df[[1]], aes(x, log.delta_pollinators)) +  
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.2) + geom_line() +
  geom_point(data = polplot0.df[[2]], 
             mapping = aes(color = margin_dens), 
             size = 0.6) + scale_color_continuous(type = "viridis") +
  facet_wrap(~pred.var, scales = "free_x") +
  egg::theme_article()

```

### Residual model from gam0

Trying to account for the effect of margins first

```{r pol_margin_resid}

wfs_lsm_resids <- wfs_lsm %>% cbind(pol.resid = residuals(pol.gam0))

polresid.gam1 <- gam(pol.resid ~ s(ann_agr_pland) + s(aglu_iji) + s(prn_agr_pland) + s(aglu_frac_mn) + s(lu_shdi), 
                data = wfs_lsm_resids)

summary(polresid.gam1)

concurvity(polresid.gam1)

```

```{r plot_pol_resid}

residpolplot.df <- plot_fun(polresid.gam1, 
                       c("ann_agr_pland", "aglu_iji", "prn_agr_pland", "aglu_frac_mn"),
                       wfs_lsm_resids,
                       "ann_agr_pland")

ggplot(residpolplot.df[[1]], aes(x, pol.resid)) +  
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.2) + geom_line() +
  geom_point(data = residpolplot.df[[2]], 
             mapping = aes(color = ann_agr_pland), 
             size = 0.6) + scale_color_continuous(type = "viridis") +
  facet_wrap(~pred.var, scales = "free_x") +
  egg::theme_article()

```

## Seasonal water yield

### Seasonal water yield delta

```{r swy_delta}

swy.lm0 <- gam(log.delta_qb ~ margin_dens, data = wfs_lsm)
swy.gam0 <- gam(log.delta_qb ~ s(margin_dens), data = wfs_lsm)

anova(swy.lm0, swy.gam0)

swy.gam1 <- gam(log.delta_qb ~ s(ann_agr_pland) + s(aglu_iji) + s(prn_agr_pland) + s(aglu_frac_mn) + s(margin_dens) + s(lu_shdi), 
                data = wfs_lsm)

performance::compare_performance(swy.lm0, swy.gam0, swy.gam1)

summary(swy.gam1)

concurvity(swy.gam1)

```

```{r plot_swy}

swyplot.df <- plot_fun(swy.gam1, 
                       c("ann_agr_pland", "aglu_iji", "prn_agr_pland", "aglu_frac_mn", "margin_dens"),
                       wfs_lsm)

ggplot(swyplot.df[[1]], aes(x, log.delta_qb)) +  
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.2) + geom_line() +
  geom_point(data = swyplot.df[[2]], 
             mapping = aes(color = margin_dens), 
             size = 0.6) + scale_color_continuous(type = "viridis") +
  facet_wrap(~pred.var, scales = "free_x") +
  egg::theme_article()

```